/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaPolar: typeof import('./components/graficos/area-polar/AreaPolar.vue')['default']
    BarrasHorizontal: typeof import('./components/graficos/barra-horizontal/BarrasHorizontal.vue')['default']
    BarrasVertical: typeof import('./components/graficos/barra-vertical/BarrasVertical.vue')['default']
    BarrasVerticalEmpilhada: typeof import('./components/graficos/barra-vertical-empilhada/BarrasVerticalEmpilhada.vue')['default']
    Bolhas: typeof import('./components/graficos/bolha/Bolhas.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CardParaComportarGraf: typeof import('./components/CardParaComportarGraf.vue')['default']
    ColunaLinhaArea: typeof import('./components/graficos/coluna-linha-area/ColunaLinhaArea.vue')['default']
    Donuts: typeof import('./components/graficos/donusts/Donuts.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    Informativo: typeof import('./components/Informativo.vue')['default']
    Linhas: typeof import('./components/graficos/linha/Linhas.vue')['default']
    MapaDeArea: typeof import('./components/graficos/mapa-de-area/MapaDeArea.vue')['default']
    Pizza: typeof import('./components/graficos/pizza/Pizza.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabela: typeof import('./components/Tabela.vue')['default']
  }
}
