/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarrasHorizontal: typeof import('./components/BarrasHorizontal.vue')['default']
    BarrasVertical: typeof import('./components/BarrasVertical.vue')['default']
    Donuts: typeof import('./components/Donuts.vue')['default']
    Filtro: typeof import('./components/Filtro.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Linhas: typeof import('./components/Linhas.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Pizza: typeof import('./components/Pizza.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabela: typeof import('./components/Tabela.vue')['default']
  }
}
