/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha1-Cards', '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha1-Cards.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/PedidoCompraPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
