/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/filtro/Components/DatasFiltro': RouteRecordInfo<'/filtro/Components/DatasFiltro', '/filtro/Components/DatasFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Components/OpcoesFiltro': RouteRecordInfo<'/filtro/Components/OpcoesFiltro', '/filtro/Components/OpcoesFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Components/PesquisaFiltro': RouteRecordInfo<'/filtro/Components/PesquisaFiltro', '/filtro/Components/PesquisaFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Filtro': RouteRecordInfo<'/filtro/Filtro', '/filtro/Filtro', Record<never, never>, Record<never, never>>,
    '/login/Login': RouteRecordInfo<'/login/Login', '/login/Login', Record<never, never>, Record<never, never>>,
    '/tema-estoque/consumo-material/components/Linha1-': RouteRecordInfo<'/tema-estoque/consumo-material/components/Linha1-', '/tema-estoque/consumo-material/components/Linha1-', Record<never, never>, Record<never, never>>,
    '/tema-estoque/consumo-material/components/Linha2-': RouteRecordInfo<'/tema-estoque/consumo-material/components/Linha2-', '/tema-estoque/consumo-material/components/Linha2-', Record<never, never>, Record<never, never>>,
    '/tema-estoque/consumo-material/ConsumoMaterial': RouteRecordInfo<'/tema-estoque/consumo-material/ConsumoMaterial', '/tema-estoque/consumo-material/ConsumoMaterial', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente', '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra', '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linha2-': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linha2-', '/tema-estoque/ponto-compra/components/Linha2-', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linhas3-': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linhas3-', '/tema-estoque/ponto-compra/components/Linhas3-', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/PontoCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/PontoCompra', '/tema-estoque/ponto-compra/PontoCompra', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/filtro/Components/DatasFiltro.vue': {
      routes: '/filtro/Components/DatasFiltro'
      views: never
    }
    'src/pages/filtro/Components/OpcoesFiltro.vue': {
      routes: '/filtro/Components/OpcoesFiltro'
      views: never
    }
    'src/pages/filtro/Components/PesquisaFiltro.vue': {
      routes: '/filtro/Components/PesquisaFiltro'
      views: never
    }
    'src/pages/filtro/Filtro.vue': {
      routes: '/filtro/Filtro'
      views: never
    }
    'src/pages/login/Login.vue': {
      routes: '/login/Login'
      views: never
    }
    'src/pages/tema-estoque/consumo-material/components/Linha1-.vue': {
      routes: '/tema-estoque/consumo-material/components/Linha1-'
      views: never
    }
    'src/pages/tema-estoque/consumo-material/components/Linha2-.vue': {
      routes: '/tema-estoque/consumo-material/components/Linha2-'
      views: never
    }
    'src/pages/tema-estoque/consumo-material/ConsumoMaterial.vue': {
      routes: '/tema-estoque/consumo-material/ConsumoMaterial'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/PedidoCompraPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linha2-.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linha2-'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linhas3-.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linhas3-'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/PontoCompra.vue': {
      routes: '/tema-estoque/ponto-compra/PontoCompra'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
