/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/filtro/Components/DatasFiltro': RouteRecordInfo<'/filtro/Components/DatasFiltro', '/filtro/Components/DatasFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Components/OpcoesFiltro': RouteRecordInfo<'/filtro/Components/OpcoesFiltro', '/filtro/Components/OpcoesFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Components/PesquisaFiltro': RouteRecordInfo<'/filtro/Components/PesquisaFiltro', '/filtro/Components/PesquisaFiltro', Record<never, never>, Record<never, never>>,
    '/filtro/Filtro': RouteRecordInfo<'/filtro/Filtro', '/filtro/Filtro', Record<never, never>, Record<never, never>>,
    '/login/Login': RouteRecordInfo<'/login/Login', '/login/Login', Record<never, never>, Record<never, never>>,
    '/tema-estoque/exemplo-graficos/components/Info-ExemploGraficos': RouteRecordInfo<'/tema-estoque/exemplo-graficos/components/Info-ExemploGraficos', '/tema-estoque/exemplo-graficos/components/Info-ExemploGraficos', Record<never, never>, Record<never, never>>,
    '/tema-estoque/exemplo-graficos/components/Linha1-ExemploDeGraficos': RouteRecordInfo<'/tema-estoque/exemplo-graficos/components/Linha1-ExemploDeGraficos', '/tema-estoque/exemplo-graficos/components/Linha1-ExemploDeGraficos', Record<never, never>, Record<never, never>>,
    '/tema-estoque/exemplo-graficos/components/Linha2-ExemploDeGraficos': RouteRecordInfo<'/tema-estoque/exemplo-graficos/components/Linha2-ExemploDeGraficos', '/tema-estoque/exemplo-graficos/components/Linha2-ExemploDeGraficos', Record<never, never>, Record<never, never>>,
    '/tema-estoque/exemplo-graficos/components/Linha3-ExemploDeGraficos': RouteRecordInfo<'/tema-estoque/exemplo-graficos/components/Linha3-ExemploDeGraficos', '/tema-estoque/exemplo-graficos/components/Linha3-ExemploDeGraficos', Record<never, never>, Record<never, never>>,
    '/tema-estoque/exemplo-graficos/ExemploGraficos': RouteRecordInfo<'/tema-estoque/exemplo-graficos/ExemploGraficos', '/tema-estoque/exemplo-graficos/ExemploGraficos', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Info-PedidoCompraPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Info-PedidoCompraPendente', '/tema-estoque/pedido-compra-pendente/components/Info-PedidoCompraPendente', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Info-Teste': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Info-Teste', '/tema-estoque/pedido-compra-pendente/components/Info-Teste', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente', '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes', Record<never, never>, Record<never, never>>,
    '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente': RouteRecordInfo<'/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Info-PontoDeCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Info-PontoDeCompra', '/tema-estoque/ponto-compra/components/Info-PontoDeCompra', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra', '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linha2-CosumoUltimos12meses': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linha2-CosumoUltimos12meses', '/tema-estoque/ponto-compra/components/Linha2-CosumoUltimos12meses', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/components/Linha3-PontoDeCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/components/Linha3-PontoDeCompra', '/tema-estoque/ponto-compra/components/Linha3-PontoDeCompra', Record<never, never>, Record<never, never>>,
    '/tema-estoque/ponto-compra/PontoCompra': RouteRecordInfo<'/tema-estoque/ponto-compra/PontoCompra', '/tema-estoque/ponto-compra/PontoCompra', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/filtro/Components/DatasFiltro.vue': {
      routes: '/filtro/Components/DatasFiltro'
      views: never
    }
    'src/pages/filtro/Components/OpcoesFiltro.vue': {
      routes: '/filtro/Components/OpcoesFiltro'
      views: never
    }
    'src/pages/filtro/Components/PesquisaFiltro.vue': {
      routes: '/filtro/Components/PesquisaFiltro'
      views: never
    }
    'src/pages/filtro/Filtro.vue': {
      routes: '/filtro/Filtro'
      views: never
    }
    'src/pages/login/Login.vue': {
      routes: '/login/Login'
      views: never
    }
    'src/pages/tema-estoque/exemplo-graficos/components/Info-ExemploGraficos.vue': {
      routes: '/tema-estoque/exemplo-graficos/components/Info-ExemploGraficos'
      views: never
    }
    'src/pages/tema-estoque/exemplo-graficos/components/Linha1-ExemploDeGraficos.vue': {
      routes: '/tema-estoque/exemplo-graficos/components/Linha1-ExemploDeGraficos'
      views: never
    }
    'src/pages/tema-estoque/exemplo-graficos/components/Linha2-ExemploDeGraficos.vue': {
      routes: '/tema-estoque/exemplo-graficos/components/Linha2-ExemploDeGraficos'
      views: never
    }
    'src/pages/tema-estoque/exemplo-graficos/components/Linha3-ExemploDeGraficos.vue': {
      routes: '/tema-estoque/exemplo-graficos/components/Linha3-ExemploDeGraficos'
      views: never
    }
    'src/pages/tema-estoque/exemplo-graficos/ExemploGraficos.vue': {
      routes: '/tema-estoque/exemplo-graficos/ExemploGraficos'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Info-PedidoCompraPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Info-PedidoCompraPendente'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Info-Teste.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Info-Teste'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha1-Cards-PedidoPendente'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha2-PedidoPendente-FornecedorAtraso'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/components/Linha3-PedidoPendente-ItensPendentes'
      views: never
    }
    'src/pages/tema-estoque/pedido-compra-pendente/PedidoCompraPendente.vue': {
      routes: '/tema-estoque/pedido-compra-pendente/PedidoCompraPendente'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Info-PontoDeCompra.vue': {
      routes: '/tema-estoque/ponto-compra/components/Info-PontoDeCompra'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linha1-CardPontoCompra'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linha2-CosumoUltimos12meses.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linha2-CosumoUltimos12meses'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/components/Linha3-PontoDeCompra.vue': {
      routes: '/tema-estoque/ponto-compra/components/Linha3-PontoDeCompra'
      views: never
    }
    'src/pages/tema-estoque/ponto-compra/PontoCompra.vue': {
      routes: '/tema-estoque/ponto-compra/PontoCompra'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
